### ISSUE TITLE
I'm doing something similar and would like to use some of this

### ISSUE THREAD

**Issue by glassresistor** [benbovy/xlrenderer#1]
Any change you could push up an example template and yaml file?  This looks really interesting and I'm considering doing something really similar in and out of the database.

If I get it working i plan on putting on pypi and would be happy to give you much credit.

**Comment by benbovy** [comment]
This project is quite old and I don't maintain it anymore. However, it indeed deserves more details about the content expected for the yaml definition file (done in #2).
